### ISSUE TITLE
Async Await & Extracting Left if isLeft()

### ISSUE THREAD

**Issue by mustafaekim** [gigobyte/pure#9]
Hi, I just try to plug the library into my project. I have 2 problems which I may wrongly approach but I could not find a solution within the library.

- How do we handle async/await inside chain or map in Either/Maybe
- How do we extract Left value  from either if it is Left without a default (isLeft() return true)
- How can I transform an Either<L1,R1> to Either<L1, R2>

my code below is an example for presenting the problems:
```ts
having:
async function getDocsByQuery<T>(query: Query): Promise<Util.Either<Util.ZetError, Doc<T>[]>> {..}
async function add(collectionRef: CollectionReference, data: any): Promise<Util.Either<Util.ZetError, string>> {..}
---
export const newUser = async function(organizationId: string, username: string, password: string, active: boolean, 
  displayName?: string, email?: string, tags?: Util.ZetTags, roles?: RoleSet): Promise<Util.Either<Util.ZetError, string>> {
  var user = bOrganizationUserData(username, password, active, displayName, email, tags, roles);
  var collection = db
    .collection("organization")
    .doc(organizationId)
    .collection("user");

  var query = collection
  .where("username", "==", username)
  .where("deleted", "==", false)
  .limit(1)
  var eitherDocs = await getDocsByQuery<OrganizationUserData>(query)
  if(eitherDocs.isRight()){
    // the first query resulted successfuly, I check how many docs returned. if no document, I can add user
    if(eitherDocs.unsafeCoerce().length==0){
      var eitherAdd = await add(collection, user)
      return eitherAdd
    }
    else{
      // there is already a doc with same username, return error
      return Util.Left(bZetError("Username already exists"))
    }    
  }
  else return Util.Left(eitherDocs.leftOrDefault(Util.bZetError("")))
   /// I need to transform the either to comply with the return type
};

```
What I try to do, is 

- I query users from the db. 
- If no error, I check how many result documents returned. If zero, I (async) add the users and return the either.
- If error, I create a new Left because the Either that getDocsByQuery returns does not comply with the return type

**Comment by gigobyte** [comment]
* How do we handle async/await inside chain or map in Either/Maybe

I advise against using async/await, as it promotes imperative style. I am working on a `Future` module that will allow for easier composition of async functions, in the meantime you can use the built-in Promise API.

*  How do we extract Left value from either if it is Left without a default (isLeft() return true)

This seems like a mistake on my part. The next version of pure will have narrowed types after using the isRight/isLeft methods, in fact the code is already done, you can install pure from this repository to try it out until the release.

* How can I transform an Either<L1,R1> to Either<L1, R2>

What you are describing looks like the `.map` method.

**Comment by mustafaekim** [comment]
is there an example for using "built-in Promise API" along with pure-ts?

I'll be waiting the "narrowed types" for the next release, thanks for informing in advance

**Comment by gigobyte** [comment]
Unfortunately, currently no. I'm always open to improvements in the docs so that will be on my to-do list.
